#+TITLE: Replication guide for political uncertainty 

* Softwares required

- Stata (version 14 or higher) 1 is used throughout the *building process*;
- RStudio(version 0.99.902 or higher), R (version 3.3.3 or higher), and RStan(Rtools 3.4 or higher) are used throughout the *analysis process*.

* Directory Structure

The replication data and program codes are organized by the following directory structure. There are three main directories, =/build=, =/analysis=, and =/writing=. Each of which contains the following four folders (some of them maybe empty)
- =/input=: data used in this step of process;
- =/code=: program files used in this step of process;
- =/temp=: store some temporary files generated in this step;
- =/output=: data or results for further analysis

** Building process

The files related are stored in folder =/build=. This process is meant to produces data from raw data for further model use and analysis. The files related are as following:
1. =/input=:
   - ~maplight_bill_position.dta~: contains the positions of interest groups across bills;
   - ~maplight_votes.dta~: represents the votes of the legislators for each action.
2. =/code=:
   - ~Generate_vote_data_for_R.do~: Stata code produces vote data used in RStan model from input above;
   - ~Generate_group_dummy_by_action.do~: Stata code generates dummy variables of which groups take positions on each bill
3. =/temp=: files in this directory are not so important and can be produced from the codes above, keep only for record.
4. =/output=:
   - ~data_for_rstan.csv~: produced by ~Generate_vote_data_for_R.do~, data file used in the RStan model;
   - ~group_dummy_for_rstan.csv~: generated by code ~Generate_group_dummy_by_action.do~, contains dummy variables for all the groups.
     
** Analysis process

This is the process of running the RStan model. The files relevant are:
1. =/input=: this folder is empty, since the input files come from output of *building process*, namely ~data_for_rstan.csv~ and ~group_dummy_for_rstan.csv~, so they are not copied here
2. =/code=: Only one program here,
   ~11_groups_5000_code.R~: the name should be modified to reflect its function but not for keeping the origin name; this program runs the RStan model, extract out results, and generate graphs of ideal point and uncertainty.
3. =/temp=: ~11_groups_vectorize.RData, ~32groups_2chains_2000iters.RData~, ~32groups_2chains_2000iters_elementwise.RData~ etc. are R workplace files stored for record.
4. =/output=: 
   - ~alpha_with_names.csv~: ideal points extracted from the model results, add legislators' names for easy analysis;
   - ~32_groups_ideal_points_group_i.png~: graph of ideal points for group i,  ~i = 1, 2, ..., number_of_groups~
     
** Writing

* Order of running the programs
  
Please run the programs in the following order. For the Stata programs, just right click the do file, and click *Execute(do)*. For the R program file, it can be ran in a whole in RStudio, ~sourece("11_groups_5000_code.R")~, or by piece(but make sure to set working directory first).

1. ~Generate_vote_data_for_R.do~
2. ~Generate_group_dummy_by_action.do~
3. ~11_groups_5000_code.R~

  
