#+TITLE: Replication guide for political uncertainty 

* Softwares required

- Stata (version 14 or higher) is used throughout the *building process*;
- RStudio (version 0.99.902 or higher), R (version 3.3.3 or higher), and RStan (Rtools 3.4 or higher) are used throughout the *analysis process*.

* Directory Structure

The replication data and program code are organized by the following directory structure. There are three main directories, =/build=, =/analysis=, and =/writing=, each of which contains the following four folders (some of them maybe empty):
- =/input=: data used in this step of process;
- =/code=: program files used in this step of process;
- =/temp=: temporary files generated in this step;
- =/output=: data or results for further analysis.

** Building process

The files related to generating the data used in analysis from the raw data are stored in folder =/build=. The files are as follows:
1. =/input=:
   - ~maplight_bill_position.dta~: contains the positions of interest groups across actions;
   - ~maplight_votes.dta~: represents the votes of the legislators for each action.
   *Note*: Most actions are for final passage of a bill, but there are multiple actions to some bills.
2. =/code=:
   - ~Generate_vote_data_for_R.do~: Stata code produces vote data used in RStan model from input above;
   - ~Generate_group_dummy_by_action.do~: Stata code generates dummy variables of which groups take positions on each bill.
   *Note*: Some old programs are preserved from before the project was under version control.
3. =/temp=: files in this directory are not so important and can be produced from the code above, keep only for record.
4. =/output=:
   - ~data_for_rstan.csv~: produced by ~Generate_vote_data_for_R.do~, data file used in the RStan model;
   - ~group_dummy_for_rstan.csv~: generated by code ~Generate_group_dummy_by_action.do~, contains dummy variables for all the groups.
     
** Analysis process

This is the process of running the RStan model. The relevant files are:
1. =/input=: this folder is empty, since the input files come from output of *building process*, namely ~data_for_rstan.csv~ and ~group_dummy_for_rstan.csv~, so they are not copied here.
2. =/code=: There is only one relevant program here,
   ~RStan_model.R~: this program runs the RStan model, extracts results, and generates graphs of ideal points and uncertainty.

   *Note*: Some old programs are preserved from before the project was under version control.
3. =/temp=: ~11_groups_vectorize.RData~, ~32groups_2chains_2000iters.RData~, ~32groups_2chains_2000iters_elementwise.RData~ etc. are R workplace files stored for record.
4. =/output=: 
   - ~alpha_with_names.csv~: ideal points extracted from the model results, with legislators' names for easy analysis;
   - ~32_groups_ideal_points_group_i.png~: graph of ideal points for group i,  ~i = 1, 2, ..., number_of_groups~
     
** Writing

* Order of running the programs
  
Please run the programs in the following order. For the Stata programs, just right click the do file, and click *Execute(do)*. For the R program file, it can be ran as a whole in RStudio, ~sourece("RStan_model.R")~, or piece by piece (but make sure to set working directory first).

1. ~Generate_vote_data_for_R.do~
2. ~Generate_group_dummy_by_action.do~
3. ~RStan_model.R~

  
